---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-demo-cluster
  region: us-west-2
  version: "1.22"
# traits of worker nodes
nodeGroups:
  - name: my-demo-workers
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 1
    maxSize: 3
    iam:
      # polices added to worker node role
      withAddonPolicies:
        # allows read/write to zones in Route53
        externalDNS: true
        # access to ACM
        certManager: true